permissions:
  wish:
    permission: 'santory.wish'
    message: '&cBạn cần làm nhiệm vụ &aHòm nhân phẩm&c để có thể dùng tính năng này! &7(/nhiemvu >> Nhiệm vụ chính)'
  enhance:
    permission: 'santory.enhance'
    message: '&cBạn cần làm nhiệm vụ &aNâng cấp&c để có thể dùng tính năng này! &7(/nhiemvu >> Nhiệm vụ chính)'
  upgrade:
    permission: 'santory.upgrade'
    message: '&cBạn cần làm nhiệm vụ &aNâng cấp&c để có thể dùng tính năng này! &7(/nhiemvu >> Nhiệm vụ chính)'
  ascent:
    permission: 'santory.ascent'
    message: '&cBạn cần làm nhiệm vụ &aNâng cấp&c để có thể dùng tính năng này! &7(/nhiemvu >> Nhiệm vụ chính)'

xacminh-success:
  - 'bc %player% xác minh không hack thành công!'

chat-prefix-default: '&2[&aMEMBER&2]'
chat-prefix:
  - 'santory.vip:&3[&bVIP&3]'
  - 'santory.hero:&5[&dHERO&5]'
  - 'santory.champion:&6[&eCHAMPION&6]'

pvp-worlds:
- world_pvp

level:
  vallina-update: false
  base-exp: 350
  plus-exp: 150

item:
  max-durability: 800
  grade-exp:
    I: 0
    II: 150
    III: 300
    IV: 450
    V: 600

ascent:
  base-chance: 50
  fee: 5000
  free-permission: 'santory.ascent.free'

upgrade:
  base-chance: 50
  fee: 500
  exp-per-material: 100

enhance:
  fee: 100
  chance:
  - '1-10:80'
  - '11-20:40'
  - '21-30:20'
  - '31-40:10'
  - '41-50:5'

artifact:
  base-main-stat: 15
  base-sub-stat: 5
  stat-range: 0.25
  tier-up:
  - 'COMMON:0'
  - 'UNCOMMON:1'
  - 'RARE:1.5'
  - 'EPIC:2'
  - 'LEGEND:2.5'
  stat-up:
  - '2:0.2'
  - '4:0.5'

mob:
  mob:
    level: 10
    type: minion

wish-key:
  key1:
    wishes:
      - armor
      - weapon
    item:
      name: '&f&lChìa trắng'
      type: IRON_INGOT
      model: 1
      lore:
        - '&7&oDùng để mở hòm Vũ khí và Giáp'
      enchant: []
      flag:
        - HIDE_ATTRIBUTES
  key2:
    wishes:
      - armor
      - weapon
      - event
    item:
      name: '&b&lChìa xanh'
      type: IRON_INGOT
      model: 2
      lore:
        - '&7&oDùng để mở tất cả loại hòm'
      enchant: []
      flag:
        - HIDE_ATTRIBUTES

die-exp-lost-percent: 25
keep-stone:
  name: '&a&lĐá bảo hộ'
  type: IRON_INGOT
  model: 2
  lore:
    - '&7&oGiúp chết không bị mất đồ'
  enchant: []
  flag:
    - HIDE_ATTRIBUTES

global-speaker:
  name: '&a&lLoa thế giới'
  type: GOLD_INGOT
  model: 2
  lore:
    - '&7&oDùng để nói chuyện liên máy chủ'
    - '&7&oCách dùng: /loa <chat>'
    - '&7&oVí dụ: /loa Chào các bạn bên MineStrike'
  enchant: []
  flag:
    - HIDE_ATTRIBUTES