name: SantoryCore
author: MankaiStep
version: 1.0
main: mk.plugin.santory.main.SantoryCore
depend: [PlayerData]
soft-depend: [PlaceholderAPI]
commands:
    santory:
        descripton: Santory's command
        aliases: [str]