name: SantoryCore
author: MankaiStep
version: 1.0
main: mk.plugin.santory.main.SantoryCore
depend: [PlayerData, HolographicDisplays]
soft-depend: [PlaceholderAPI]
api-version: 1.13
commands:
    santory:
        descripton: Santory's command
        aliases: [str]
    artifact:
        description: Artifacts
        aliases: [divat]
    forge:
        description: Forges
        aliases: [tiemren]
    see:
        description: Sees
        aliases: [xem]
    player:
        description: Info
        aliases: [me, ditme]